name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw6-dev \  # Замена для libtinfo5 в Ubuntu 24.04
            libtinfo6 \         # Альтернативный пакет
            git \
            unzip \
            zip
        
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip wheel
        pip install cython==0.29.33 buildozer
        
    - name: Run Buildozer
      run: |
        buildozer init
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk