name: Build Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-dev \
            python3-pip \
            openjdk-8-jdk \
            zlib1g-dev \
            libncurses5-dev \
            libtinfo5 \
            git \
            unzip \
            zip \
            libssl-dev \
            libffi-dev

    - name: Clean up disk space
      run: |
        df -h
        sudo apt-get clean
        sudo apt-get autoremove -y
        df -h

    - name: Install Buildozer with dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install --user cython==0.29.33
        pip install --user buildozer==1.4.0 Pillow

    - name: Build APK with debug info
      run: |
        buildozer -v android debug 2>&1 | tee build.log
        echo "Build log saved to build.log"
        
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-log
        path: build.log

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk